# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "5933c2e4517c47713d3c7c90a7589721"
name = "warhouse app testing"
application_url = "https://municipality-andreas-snap-renewal.trycloudflare.com"
embedded = true
handle = "warhouse-app-testing"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_products,read_orders,write_orders,read_customers,write_customers"

[auth]
redirect_urls = ["https://municipality-andreas-snap-renewal.trycloudflare.com/auth/callback", "https://municipality-andreas-snap-renewal.trycloudflare.com/auth/shopify/callback", "https://municipality-andreas-snap-renewal.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
